module ejemplo {
    interface Calculadora {
        long sumar(
            in long a,
            in long b
        );


        long restar(
            in long a,
            in long b
        );

    };


};